[fix]scripts-batctl: Fix typo in error message

diff --git a/scripts/system/batctl b/scripts/system/batctl
--- a/scripts/system/batctl
+++ b/scripts/system/batctl
@@ -2,7 +2,7 @@
 
 # Check for batctl existence
 if ! command -v batctl >/dev/null; then
-    echo "Fatal: Couldn't find dunstctl." >&2
+    echo "Fatal: Couldn't find batctl." >&2
     exit 1
 fi
 
